### ISSUE TITLE
How to use php-l20n ?

### ISSUE THREAD

**Issue by SunboX** [tisogawa/php-l20n#1]
See title, how do I use it :question:

**Comment by tisogawa** [comment]
Please note that since it is an experimental implementation of only the parser and the compiler of the original, and is based on the older version, I do not recommend it if you are looking for a PHP equivalent of the original L20n.

For the use of the compiler, you may check [CompilerTest](https://github.com/tisogawa/php-l20n/blob/master/tests/L20n/CompilerTest.php)

**Comment by SunboX** [comment]
Thanks a lot, works great!

If someone comes across this, the code I've used:

``` php

$languageFile = new SplFileObject(__DIR__ . DIRECTORY_SEPARATOR . 'locales' . DIRECTORY_SEPARATOR . $_SESSION['LANGUAGE'] . '.l20n');
$languageL20n = '';
while (!$languageFile->eof()) {
    $languageL20n .= $languageFile->fgets();
}

$l20nParser = new L20n\Parser();
$l20nCompiler = new L20n\Compiler();

$_SESSION['L10N'] = $l20nCompiler->compile($l20nParser->parse($languageL20n));

echo $_SESSION['L10N']->appName->getString();
```

And my Composer config:

``` json
{
    "require": {
        "php": ">=5.4",
        "ext-json": "*",
        //...
    },
    "autoload": {
        "psr-0": {
            "": [
                //"classes/",
                //"entities/"
            ],
            "L20n": "classes/php-l20n/src"
        }
    }
}
```

**Comment by tisogawa** [comment]
For composer.json, as this is an experimental release and I haven't registered it to packagist.org, you may explicitly specify the repository URL in your composer.json like:

``` json
{
  "require": {
    "tisogawa/php-l20n": "dev-master"
  },  
  "repositories": [
    {   
      "type": "vcs",
      "url": "git@github.com:tisogawa/php-l20n.git"
    }   
  ]
}
```

**Comment by SunboX** [comment]
Oh, nice. Thanks for the hint! :smile:
