### ISSUE TITLE
Parser Error on PHP 5.4.39 (works on 5.6.0)

### ISSUE THREAD

**Issue by SunboX** [tisogawa/php-l20n#2]
Fails on PHP Version 5.4.39-0+deb7u2 (Linux)
Works on PHP Version 5.6.0 (Windows)

Parsing this string:

``` l20n
<loggedInAsUSERNAME "Logged in as {{ $user.realname }}">
```

Fails with:

``` text
<b>Parse error</b>:  syntax error, unexpected '{' in <b>/srv/htdocs/vendor/tisogawa/php-l20n/src/L20n/Compiler/Expression/ComplexString.php</b> on line <b>82</b><br />
```

User Object:

``` php
$LANGUAGE_ATTRIBUTES = new stdClass();
$LANGUAGE_ATTRIBUTES->user = new stdClass();
$LANGUAGE_ATTRIBUTES->user->realname = 'Test';
```

**Comment by tisogawa** [comment]
Oops, my fault.

There is a finally block in the line in question, so the required PHP version should have been **5.5 or later**. I've updated the version in composer.json.

In the meantime, in case if you need to use it with PHP 5.4, I've created ["no-finally" branch](https://github.com/tisogawa/php-l20n/tree/no-finally) where I removed all finally blocks ([diff is here](https://github.com/tisogawa/php-l20n/pull/3/files)). With that branch over PHP 5.4.39, I confirmed the following code, as well as the existing tests are working as expected.

``` php
$source = '<loggedInAsUSERNAME "Logged in as {{ $user.realname }}">';
$data = '{"user": {"realname": "Test"}}';

$parser = new L20n\Parser();
$compiler = new L20n\Compiler();
$ast = $parser->parse($source);
$entity = $compiler->compile($ast);
$string = $entity->loggedInAsUSERNAME->getString(json_decode($data));
assert($string === 'Logged in as Test');
```

**Comment by SunboX** [comment]
Works great! Thank you very much! :smile:
